"""
train.py — SkillNet ML skill level classifier training script.
Run: python train.py
Reads: dataset.csv (generated by generate_dataset.py)
Outputs: skill_model.pkl, scaler.pkl, label_encoder.pkl

To add more training data, append rows to dataset.csv in the format:
  score_pct,time_taken_sec,easy_correct,medium_correct,hard_correct,attempt_number,label

Example row:
  85.0,240,3,4,2,1,Advanced
"""

import numpy as np
import pandas as pd
import pickle
import os
import sys
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# ── Reproducibility ──────────────────────────────────────────────────────────
np.random.seed(42)

# ── Load dataset from CSV ────────────────────────────────────────────────────
script_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(script_dir, "dataset.csv")

if not os.path.exists(csv_path):
    print(f"[ERROR] Dataset not found: {csv_path}")
    print("Run 'python generate_dataset.py' first to create the initial dataset.")
    sys.exit(1)

df = pd.read_csv(csv_path)

# ── Validate dataset ─────────────────────────────────────────────────────────
FEATURE_COLS = [
    "score_pct", "time_taken_sec", "easy_correct",
    "medium_correct", "hard_correct", "attempt_number"
]
LABEL_COL = "label"
REQUIRED_COLS = FEATURE_COLS + [LABEL_COL]

missing_cols = [c for c in REQUIRED_COLS if c not in df.columns]
if missing_cols:
    print(f"[ERROR] Missing columns in dataset.csv: {missing_cols}")
    print(f"Required columns: {REQUIRED_COLS}")
    sys.exit(1)

# Drop rows with missing values (if any)
before = len(df)
df = df.dropna(subset=REQUIRED_COLS)
if len(df) < before:
    print(f"[WARN] Dropped {before - len(df)} rows with missing values")

# Validate label values
valid_labels = {"Beginner", "Intermediate", "Advanced"}
invalid_labels = set(df[LABEL_COL].unique()) - valid_labels
if invalid_labels:
    print(f"[ERROR] Invalid label values found: {invalid_labels}")
    print(f"Allowed labels: {valid_labels}")
    sys.exit(1)

print(f"[OK] Loaded {len(df)} records from {csv_path}")
print()
print("Label distribution:")
print(df[LABEL_COL].value_counts().to_string())
print()

# ── Features & target ────────────────────────────────────────────────────────
X = df[FEATURE_COLS].values
y = df[LABEL_COL].values

# ── Encode labels ─────────────────────────────────────────────────────────────
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
print(f"Label classes: {label_encoder.classes_}")

# ── Train / test split ────────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.20, random_state=42, stratify=y_encoded
)

# ── Scale features ────────────────────────────────────────────────────────────
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ── Train model ───────────────────────────────────────────────────────────────
model = LogisticRegression(solver="lbfgs", max_iter=500, C=1.0, random_state=42)
model.fit(X_train_scaled, y_train)

# ── Evaluate ──────────────────────────────────────────────────────────────────
y_pred = model.predict(X_test_scaled)

print("=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

print("CONFUSION MATRIX")
print("=" * 60)
cm = confusion_matrix(y_test, y_pred)
print(f"Classes: {label_encoder.classes_}")
print(cm)
print()

# ── Save artifacts ────────────────────────────────────────────────────────────
model_path   = os.path.join(script_dir, "skill_model.pkl")
scaler_path  = os.path.join(script_dir, "scaler.pkl")
encoder_path = os.path.join(script_dir, "label_encoder.pkl")

with open(model_path, "wb")   as f: pickle.dump(model, f)
with open(scaler_path, "wb")  as f: pickle.dump(scaler, f)
with open(encoder_path, "wb") as f: pickle.dump(label_encoder, f)

print(f"[OK] Saved: {model_path}")
print(f"[OK] Saved: {scaler_path}")
print(f"[OK] Saved: {encoder_path}")
print()
print("Training complete. Run 'python api.py' to start the prediction server.")
